services:
  database:
    image: pgvector/pgvector:pg16
    command: -c 'max_connections=500'
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./../skilllevel_service/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_CREATE_DB_SKILLLEVEL_SERVICE=skilllevel_service
  app-skilllevel:
    build:
      context: ./../skilllevel_service # necessary because otherwise docker-compose overrides the context path when merging multiple docker-compose.yml files
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - database
    links:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/skilllevel_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  dapr-skilllevel:
    image: "daprio/daprd"
    command: [
      "./daprd",
      "--app-id", "skilllevel_service",
      "--app-port", "8001",
      "--dapr-http-port", "8000",
      "--resources-path", "./components"
    ]
    volumes:
      - "./../skilllevel_service/components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - app-skilllevel
      - redis
    network_mode: "service:app-skilllevel"
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  dbdata:
  testdata:
networks:
  default:
    name: dapr-network
    external: true